version: "3"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: localdev
      POSTGRES_PASSWORD: localDev
      POSTGRES_DB: UCR
    volumes:
      - ./.init:/docker-entrypoint-initdb.d

  es:
    image: elasticsearch:8.12.1
    platform: linux/arm64
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
