version: "3"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: localdev
      POSTGRES_PASSWORD: localDev
      POSTGRES_DB: UCR
    volumes:
      - ./.init:/docker-entrypoint-initdb.d